name: Check Player Progressions
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install axios googleapis
      - name: Check progressions
        env:
          DISCORDWEBHOOKURL: ${{ secrets.DISCORDWEBHOOKURL }}
          GOOGLESHEETSCREDENTIALS: ${{ secrets.GOOGLESHEETSCREDENTIALS }}
          GOOGLESHEETID: ${{ secrets.GOOGLESHEETID }}
        run: node scripts/checkProgressions.js
